"use strict";
exports.__esModule = true;
var TestTaskMap_1 = require("./TestTaskMap");
var TestTaskFold_1 = require("./TestTaskFold");
var TestTaskMapByFold_1 = require("./TestTaskMapByFold");
console.log("____________________Map________________________");
console.log("_______________________________________________");
console.log("newMap([1,2,3,4], x => x + 1) = [2,3,4,5]");
console.log("Answer: ", TestTaskMap_1.addOneRes);
console.log("_______________________________________________\n");
console.log("_______________________________________________");
console.log("newMap([1,2,3,4], x => x ** 2) = [1,4,9,16]");
console.log("Answer: ", TestTaskMap_1.squareEachRes);
console.log("_______________________________________________\n");
console.log("_______________________________________________");
console.log("newMap([1,2,3,4], x => x.toString()) = ['1','2','3','4']");
console.log("Answer: ", TestTaskMap_1.numToString);
console.log("_______________________________________________\n\n\n");
console.log("_____________________Fold_______________________");
console.log("Fold([1,2,3,4], 0, (sum, item) => sum + item) = 10");
console.log("Answer: ", TestTaskFold_1.sumOfArrEl);
console.log("_______________________________________________\n");
console.log("_______________________________________________");
console.log("Fold([1,2,3,4], '', (sum, item) => sum + item.toString()) = '1234'");
console.log("Answer: ", TestTaskFold_1.arrToString);
console.log("_______________________________________________\n\n\n");
console.log("___________________Map_by_Fold___________________");
console.log("mapByFold([1,2,3,4], x => x + 1) = [2,3,4,5]");
console.log("Answer: ", TestTaskMapByFold_1.addOneRess);
console.log("_______________________________________________\n");
console.log("_______________________________________________");
console.log("mapByFold([1,2,3,4], x => x ** 2) = [1,4,9,16]");
console.log("Answer: ", TestTaskMapByFold_1.squareEachRess);
console.log("_______________________________________________\n");
console.log("_______________________________________________");
console.log("mapByFold([1,2,3,4], x => x.toString()) = ['1','2','3','4']");
console.log("Answer: ", TestTaskMapByFold_1.numToStringg);
console.log("_______________________________________________\n");
